### ISSUE TITLE
Support to AlpineJS v3

### ISSUE THREAD

**Issue by danpalmieri** [livewire-ui/modal#51]
Please, add support to AlpineJS v3. Thanks a lot! Great package!!!

**Comment by gcw07** [comment]
This is a livewire package, so until livewire itself supports Alpine 3, there isn't a lot that can be done.

**Comment by PhiloNL** [comment]
https://twitter.com/calebporzio/status/1404456562777800708?s=21 soon 😄

**Comment by SuddenlyRust** [comment]
And Alpine v3 support is added to Livewire 🥳 https://github.com/livewire/livewire/releases

I only needed to import the Modal JS before Alpine to get it working 👍 

```js
// Import Livewire UI Modal
require('../../vendor/livewire-ui/modal/resources/js/modal.js')

// Import Alpine
import Alpine from 'alpinejs'

window.Alpine = Alpine

Alpine.start()
```

**Comment by PhiloNL** [comment]
The modal indeed works fine with Alpine v3 and doesn't require any changes 😄 I've updated the readme to include the Alpine v3 CDN.

**Comment by RobertCordes** [comment]
In case anyone is still getting errors after upgrading to Alpine v3: in my case it helped to include this line

```js
window.Alpine = Alpine
```

I know the official documentation already tells us to include this line, but I never do. 😅
